apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''

    [smtp]                                                                                                                                                                                                            
    enabled = true                                                                                                                                                                                                    
    host = smtp.gmail.com:587                                                                                                                                                                                         
    user = stefansnihur@gmail.com                                                                                                                                                                                     
    password = koacpvuakchjehyh                                                                                                                                                                                       
    from_address = grafana@gmail.com                                                                                                                                                                                  
    from_name = Grafana                                                                                                                                                                                               
    ehlo_identity = localhost 

kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: bestrong-api
  creationTimestamp: "2024-12-17T22:43:21Z"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.4.0
    helm.sh/chart: grafana-8.8.2
  name: prometheus-grafana
  namespace: bestrong-api
  resourceVersion: "379126"
  uid: b202c517-83cf-4504-9479-c14218a5953a